### ISSUE TITLE
Error Deploying Policy

### ISSUE THREAD

**Issue by sidd-harth** [mulesoft-catalyst/canary-policy-mule-4#1]
Hey @panizzag, I was trying this and `mvn clean install` gives following,

Could you please let me know how to debug/fix this?

I am looking to use this for app deployed on RTF. 

`Could not resolve dependencies for project 7c6xxxxxxxxxxff502d:canarypolicy:mule-policy:1.2.3: The following artifacts could not be resolved: com.mulesoft.anypoint:mule-http-policy-transform-extension:jar:mule-plugin:3.1.0, org.mule.connectors:mule-objectstore-connector:jar:mule-plugin:1.1.1: Failure to find com.mulesoft.anypoint:mule-http-policy-transform-extension:jar:mule-plugin:3.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

**Comment by panizzag** [comment]
Hi @sidd-harth 
Could you please share what are the repositories you have in your settings.xml? (please mask or change the credentials before sharing)

Thanks,
GP

**Comment by sidd-harth** [comment]
I missed adding the mule Nexus repo credentials.    I reached out to my infra team to get the credentials. I hope that will solve the issue.

Well update this thread after trying the credentials.

Thanks

**Comment by panizzag** [comment]
Hi @sidd-harth , doing a follow-up on this one. Were you able to test the credentials?

Thanks,
GP

**Comment by sidd-harth** [comment]
I couldn't test this as I didn't get the Mule EE credentials.

**Comment by panizzag** [comment]
Thanks for the update @sidd-harth . Will close this issue and after you get the credentials you can test and open a new one if needed.
Thanks,
GP
