### ISSUE TITLE
Canary Policy is not working and its throwing 500

### ISSUE THREAD

**Issue by Jitendra85** [mulesoft-catalyst/canary-policy-mule-4#2]
Hi,

I was trying to test Mule 4 Canary policies. I have one api deployed with Auto Discovery enabled and deployed new version of api separately. Now i have applied Canary Policy on first version of API and setup Canary host and other canary parameters to new version of api and Original host and original parameter to first version of api. It is throwing 500 while testing.

Some Logs

14:40:00.275     11/07/2021     Worker-0     [MuleRuntime].uber.09: [canary-release-mule4-2287878-circuit-breaker-policyFlow].2287878-custom-policy.CPU_LITE @119a4216     DEBUG
event:7c387df0-3faa-11ec-8b1e-0297a2da437e Before creating weights array
14:40:00.300     11/07/2021     Worker-0     [MuleRuntime].uber.09: [canary-release-mule4-2287878-circuit-breaker-policyFlow].2287878-custom-policy.CPU_LITE @119a4216     DEBUG
event:7c387df0-3faa-11ec-8b1e-0297a2da437e [
  {
    "url": "HTTP://mule-worker-circuit-breaker-app.de-c1.cloudhub.io:8081/api/v1/",
    "weight": 50
  },
  {
    "url": "HTTP://mule-worker-circuit-breaker-app-v2.de-c1.cloudhub.io:8081/api/v2/",
    "weight": 50
  }
]
14:40:00.376     11/07/2021     Worker-0     [MuleRuntime].uber.09: [canary-release-mule4-2287878-circuit-breaker-policyFlow].2287878-custom-policy.CPU_LITE @119a4216     DEBUG
event:7c387df0-3faa-11ec-8b1e-0297a2da437e {
  "headers": {
    "host": "circuit-breaker-app.de-c1.cloudhub.io",
    "x-real-ip": "106.209.224.49",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "authorization": "Basic MjY0MWRkMDA0YjM4ODk3MjM5ZjM4MmJhMzFhNzBhZDMyMDA1MzRmMDoxMnJ3cmVyZQ==",
    "postman-token": "66907e64-23a3-444c-9362-031712d603c8",
    "user-agent": "PostmanRuntime/7.28.4",
    "x-forwarded-for": "106.209.224.49",
    "x-forwarded-port": "80",
    "x-forwarded-proto": "http"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {
    "name": "Jit"
  },
  "requestUri": "/api/v1/test?name=Jit",
  "queryString": "name=Jit",
  "version": "HTTP/1.1",
  "maskedRequestPath": null,
  "listenerPath": "/api/v1/test",
  "relativePath": "/test",
  "localAddress": "/10.99.0.119:8081",
  "uriParams": {
    
  },
  "rawRequestUri": "/api/v1/test?name=Jit",
  "rawRequestPath": "/api/v1/test",
  "remoteAddress": "/3.123.40.163:58946",
  "requestPath": "/api/v1/test"
}

**Comment by panizzag** [comment]
Hi @Jitendra85 , are you still facing this issue?

Sorry, but I'm not able to provide any pointers with these logs. Could you please try the following deployment architecture:
- v1 (Baseline)
- v2 (Canary)
- Proxy on top

In addition:
- could you please enable the [HTTP Wire Logging](https://help.mulesoft.com/s/article/How-to-Enable-HTTP-Wire-Logging)?
- provide APIs logs (v1 & v2)

*NOTE*: Please, do not publish stack traces with sensible information like authorization header, tokens or IPs.

Thanks,
GP

**Comment by panizzag** [comment]
Hi @Jitendra85 , closing this issue as I haven't heard back for some time and I'm using the policy without issues. Please feel free to reopen this if you're still facing problems.
Regards,
GP
